POST http://localhost:3000/api/1.0/users/token/56b7ee8273308a17
Content-Type: application/json

{
	"username": "user1",
	"email": "user1@mail.com",
	"password": "P4ssword"
}

###

GET http://localhost:3000/api/1.0/users
Content-Type: application/json